# Generated by Django 5.1 on 2024-09-11 05:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(blank=True, error_messages={'max_length': 'Postal code cannot be longer than 10 digits.'}, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Postal code must contain between 1 and 10 digits.', regex='^\\d{1,10}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default.png', upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='postal_code',
            field=models.CharField(error_messages={'max_length': 'Postal code cannot be longer than 20 characters.'}, max_length=20, validators=[django.core.validators.RegexValidator(message='Postal code must contain between 1 and 10 digits.', regex='^\\d{1,10}$')]),
        ),
    ]
