# Generated by Django 5.1 on 2024-08-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingdetails',
            name='order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_fee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=0.0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='Default City', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='ShippingDetails',
        ),
    ]
