# Generated by Django 5.1 on 2024-09-05 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_salesreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, help_text='Enter your full address.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, help_text='Enter your city of residence.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter your phone number with the country code, e.g., +1234567890.', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+1234567890'. Up to 15 digits allowed.", regex='^\\+?\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Enter your postal code.', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Postal code must contain between 4 and 10 digits.', regex='^\\d{4,10}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', help_text='Upload a profile picture. If left blank, the default picture will be used.', upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='address',
            field=models.CharField(help_text='Enter your full address.', max_length=255),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='city',
            field=models.CharField(help_text='Enter your city of delivery.', max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='postal_code',
            field=models.CharField(help_text='Enter your postal code.', max_length=20, validators=[django.core.validators.RegexValidator(message='Postal code must contain between 4 and 10 digits.', regex='^\\d{4,10}$')]),
        ),
    ]
