# Generated by Django 5.1 on 2024-09-07 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_order_shipping_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, error_messages={'max_length': 'Address cannot be longer than 255 characters.'}, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, error_messages={'max_length': 'City name cannot be longer than 100 characters.'}, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='City name must contain only letters and spaces.', regex='^[a-zA-Z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'max_length': 'Phone number cannot be longer than 15 characters.'}, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+1234567890'. Up to 15 digits allowed.", regex='^\\+?\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(blank=True, error_messages={'max_length': 'Postal code cannot be longer than 20 characters.'}, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Postal code must contain between 4 and 10 digits.', regex='^\\d{4,10}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='address',
            field=models.CharField(error_messages={'max_length': 'Address cannot be longer than 255 characters.'}, max_length=255),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='city',
            field=models.CharField(error_messages={'max_length': 'City name cannot be longer than 100 characters.'}, max_length=100, validators=[django.core.validators.RegexValidator(message='City name must contain only letters and spaces.', regex='^[a-zA-Z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='postal_code',
            field=models.CharField(error_messages={'max_length': 'Postal code cannot be longer than 20 characters.'}, max_length=20, validators=[django.core.validators.RegexValidator(message='Postal code must contain between 4 and 10 digits.', regex='^\\d{4,10}$')]),
        ),
    ]
